// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD61d1bnvyzE4A7hzExdoTicKKdOb64-XU',
    appId: '1:1040802538083:web:6fc541bd29f4888fde4e56',
    messagingSenderId: '1040802538083',
    projectId: 'staff-crud-app-3a3bc',
    authDomain: 'staff-crud-app-3a3bc.firebaseapp.com',
    storageBucket: 'staff-crud-app-3a3bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEkv1wO-AZ2jn_OFOPZY5IEhdvjwUreJM',
    appId: '1:1040802538083:android:1533d875a0a46c6bde4e56',
    messagingSenderId: '1040802538083',
    projectId: 'staff-crud-app-3a3bc',
    storageBucket: 'staff-crud-app-3a3bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5gMuQSrxPLM1uAyp0LI1ohLsaoCmd_E4',
    appId: '1:1040802538083:ios:ade0a4f1527d8964de4e56',
    messagingSenderId: '1040802538083',
    projectId: 'staff-crud-app-3a3bc',
    storageBucket: 'staff-crud-app-3a3bc.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5gMuQSrxPLM1uAyp0LI1ohLsaoCmd_E4',
    appId: '1:1040802538083:ios:ade0a4f1527d8964de4e56',
    messagingSenderId: '1040802538083',
    projectId: 'staff-crud-app-3a3bc',
    storageBucket: 'staff-crud-app-3a3bc.firebasestorage.app',
    iosBundleId: 'com.example.staffCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD61d1bnvyzE4A7hzExdoTicKKdOb64-XU',
    appId: '1:1040802538083:web:f8665e98ba9f1677de4e56',
    messagingSenderId: '1040802538083',
    projectId: 'staff-crud-app-3a3bc',
    authDomain: 'staff-crud-app-3a3bc.firebaseapp.com',
    storageBucket: 'staff-crud-app-3a3bc.firebasestorage.app',
  );
}
